// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDSgBDmpFBZatY5CsB60nkkgBg1mfpiU',
    appId: '1:207736657234:web:0965cadf2d7f50ac25568b',
    messagingSenderId: '207736657234',
    projectId: 'jasimtok-b144f',
    authDomain: 'jasimtok-b144f.firebaseapp.com',
    storageBucket: 'jasimtok-b144f.firebasestorage.app',
    measurementId: 'G-57JRGPV3E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrgPUe3oygk3atKwv7AFqg9y5paTn3cgc',
    appId: '1:207736657234:android:e6202d6ad6eff7f425568b',
    messagingSenderId: '207736657234',
    projectId: 'jasimtok-b144f',
    storageBucket: 'jasimtok-b144f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhOkhQq4o2XZ4G_MdYUpqwRT04X_-H_t4',
    appId: '1:207736657234:ios:c1533e863124ed9925568b',
    messagingSenderId: '207736657234',
    projectId: 'jasimtok-b144f',
    storageBucket: 'jasimtok-b144f.firebasestorage.app',
    iosBundleId: 'inc.flutterSocialAppUiKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhOkhQq4o2XZ4G_MdYUpqwRT04X_-H_t4',
    appId: '1:207736657234:ios:c1533e863124ed9925568b',
    messagingSenderId: '207736657234',
    projectId: 'jasimtok-b144f',
    storageBucket: 'jasimtok-b144f.firebasestorage.app',
    iosBundleId: 'inc.flutterSocialAppUiKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARDSgBDmpFBZatY5CsB60nkkgBg1mfpiU',
    appId: '1:207736657234:web:94b5a7f49c487fb825568b',
    messagingSenderId: '207736657234',
    projectId: 'jasimtok-b144f',
    authDomain: 'jasimtok-b144f.firebaseapp.com',
    storageBucket: 'jasimtok-b144f.firebasestorage.app',
    measurementId: 'G-Y7HHDV8KLK',
  );

}